sonar.projectName=Vietnam ChronoGIS
sonar.sources=vietnam_chronogis/lib
sonar.tests=vietnam_chronogis/test
sonar.sourceEncoding=UTF-8
sonar.dart.lcov.reportPaths=vietnam_chronogis/coverage/lcov.info

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gr.dart,**/build/**,**/.dart_tool/**,vietnam_chronogis/android/**,vietnam_chronogis/ios/**,vietnam_chronogis/linux/**,vietnam_chronogis/macos/**,vietnam_chronogis/web/**,vietnam_chronogis/windows/**
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gr.dart,vietnam_chronogis/lib/main.dart
